spring:
  application:
    name: fuzzy-matching-engine
  datasource:
    url: jdbc:h2:~/test
    username: sa
    driver-class-name: org.h2.Driver
    platform: h2
    password: sa
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8888
